name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 3.26.228.237
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git clone https://github.com/Luxlon/uts-cloud.git ecommerce-app || true
            cd ecommerce-app
            git pull origin main
            npm install
            pm2 stop all || true
            pm2 start app.js
